version: '3.8'
services:
  mysql:
    image: mysql:latest
    container_name: mysql_database
    restart: on-failure
    hostname: my-container
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: store_management
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql
networks:
  store-management:

volumes:
  mysql_data: