#spring.application.name=store
server:
  port: 8089
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/store_management?useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect